font:
  size: 15.0
  normal:
    family: Hack Nerd Font
    style: Regular

shell:
  program: /bin/zsh
  args:
    - -l
    - -c
    - "tmux attach || tmux"

window:
  alt_send_esc: true
  option_as_alt: Both
  decorations: buttonless
  opacity: 0.7
  startup_mode: Maximized

cursor:
  style:
    shaPe: block
    blinking: on
