[cursor.style]
blinking = "on"
shape = "Block"

[font]
size = 15.0

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/bin/zsh"

[window]
decorations = "buttonless"
opacity = 0.7
option_as_alt = "Both"
startup_mode = "Maximized"
